# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: IIT ROBOTICS
author: Daniela Moraes
description: > # this means to ignore newlines until "baseurl:"
  We will look at robots as prostheses that augment the built environment, adding human elements of whimsy, personality, behavior, mobility, conflict, agency and freedom through technological proxies to otherwise static structures or empty spaces.
 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://danielamoraes.github.io" # the base hostname & protocol for your site
permalink: /:year/:month/:day/:title/
paginate: 6
paginate_path: "/page/:num/"
github_username:  DanielaMoraes
gems: [DanielaMoraes-paginate]

# Build settings
markdown: kramdown
